require('dotenv').config();
const mongoose = require('mongoose');
const { connectDB } = require('./src/config/database');
const PrivateCoupon = require('./src/models/PrivateCoupon');
const logger = require('./src/utils/logger');

const coupons = [
    { "brandName": "Blinkit", "couponTitle": "Flat ₹60 OFF on grocery orders", "category": "Grocery", "expiryDate": "2026-02-03", "daysUntilExpiry": 15, "description": "Applicable on selected grocery items.", "couponCode": "BLINK60", "redeemable": true, "minimumOrderValue": "₹299", "couponLink": "https://blinkit.com/deals/60off" },
    { "brandName": "Blinkit", "couponTitle": "Buy 2 get 1 FREE on snacks", "category": "Snacks", "expiryDate": "2026-02-12", "daysUntilExpiry": 24, "description": "Valid on chips, biscuits and confectionaries.", "couponCode": "SNACKB21", "redeemable": true, "minimumOrderValue": "₹199", "couponLink": "https://blinkit.com/deals/b2g1" },
    { "brandName": "Blinkit", "couponTitle": "₹75 OFF on fresh fruits", "category": "Fruits", "expiryDate": "2026-01-30", "daysUntilExpiry": 11, "description": "Offer valid on apples, bananas, citrus & seasonal fruits.", "couponCode": "FRUIT75", "redeemable": true, "minimumOrderValue": "₹249", "couponLink": "https://blinkit.com/deals/fruits75" },
    { "brandName": "Blinkit", "couponTitle": "Flat 10% OFF on dairy products", "category": "Dairy", "expiryDate": "2026-02-07", "daysUntilExpiry": 19, "description": "Valid on milk, butter, paneer & cheese.", "couponCode": "DAIRY10", "redeemable": true, "minimumOrderValue": "₹149", "couponLink": "https://blinkit.com/deals/dairy10" },
    { "brandName": "Blinkit", "couponTitle": "₹120 OFF on monthly essentials", "category": "Grocery", "expiryDate": "2026-02-15", "daysUntilExpiry": 27, "description": "Applicable on bulk purchase of essentials.", "couponCode": "ESSENT120", "redeemable": true, "minimumOrderValue": "₹799", "couponLink": "https://blinkit.com/deals/essentials" },
    { "brandName": "Zomato", "couponTitle": "Flat 20% OFF on all food orders", "category": "Food", "expiryDate": "2026-02-02", "daysUntilExpiry": 14, "description": "Applicable on restaurant orders across supported cities.", "couponCode": "ZOM20", "redeemable": true, "minimumOrderValue": "₹149", "couponLink": "https://zomato.com/deals/20off" },
    { "brandName": "Zomato", "couponTitle": "₹100 Cashback on first order", "category": "Food", "expiryDate": "2026-02-10", "daysUntilExpiry": 22, "description": "Valid for new users placing first order via Zomato app.", "couponCode": "ZOMFIRST100", "redeemable": true, "minimumOrderValue": "₹199", "couponLink": "https://zomato.com/deals/first100" },
    { "brandName": "Zomato", "couponTitle": "Flat 10% OFF on desserts", "category": "Food", "expiryDate": "2026-02-06", "daysUntilExpiry": 18, "description": "Valid on bakeries, ice creams and dessert chains.", "couponCode": "ZOMSWEET10", "redeemable": true, "minimumOrderValue": "₹129", "couponLink": "https://zomato.com/deals/desserts10" },
    { "brandName": "Zomato", "couponTitle": "Buy 1 Get 1 Free on pizza", "category": "Food", "expiryDate": "2026-01-31", "daysUntilExpiry": 12, "description": "Applicable on selected pizza outlets.", "couponCode": "ZOMPIZZA", "redeemable": true, "minimumOrderValue": "₹249", "couponLink": "https://zomato.com/deals/bogo-pizza" },
    { "brandName": "Zomato", "couponTitle": "15% OFF on late night orders", "category": "Food", "expiryDate": "2026-02-14", "daysUntilExpiry": 26, "description": "Offer valid between 11 PM to 4 AM only.", "couponCode": "ZOMNIGHT15", "redeemable": true, "minimumOrderValue": "₹299", "couponLink": "https://zomato.com/deals/night15" },
    { "brandName": "Phone Pay", "couponTitle": "₹50 Cashback on utility payments", "category": "Bills", "expiryDate": "2026-02-05", "daysUntilExpiry": 17, "description": "Valid on bill payments above ₹300.", "couponCode": "PPBILL50", "redeemable": true, "minimumOrderValue": "₹300", "couponLink": "https://phonepe.com/paybills" },
    { "brandName": "Phone Pay", "couponTitle": "Flat ₹30 OFF on DTH recharge", "category": "Recharge", "expiryDate": "2026-02-08", "daysUntilExpiry": 20, "description": "Valid once per user during campaign period.", "couponCode": "PPDTH30", "redeemable": true, "minimumOrderValue": "₹200", "couponLink": "https://phonepe.com/dth" },
    { "brandName": "Phone Pay", "couponTitle": "₹75 Cashback on FASTag recharge", "category": "Transport", "expiryDate": "2026-02-11", "daysUntilExpiry": 23, "description": "Applicable to FASTag recharge above ₹500.", "couponCode": "PPFAST75", "redeemable": true, "minimumOrderValue": "₹500", "couponLink": "https://phonepe.com/fastag" },
    { "brandName": "Phone Pay", "couponTitle": "₹100 Cashback on mutual fund buy", "category": "Finance", "expiryDate": "2026-02-18", "daysUntilExpiry": 30, "description": "Valid for new MF users above minimum investment.", "couponCode": "PPMF100", "redeemable": true, "minimumOrderValue": "₹1000", "couponLink": "https://phonepe.com/mutualfunds" },
    { "brandName": "Phone Pay", "couponTitle": "₹40 Cashback on mobile recharge", "category": "Recharge", "expiryDate": "2026-01-29", "daysUntilExpiry": 10, "description": "Applicable once per month for all users.", "couponCode": "PPMOB40", "redeemable": true, "minimumOrderValue": "₹199", "couponLink": "https://phonepe.com/mobile" },
    { "brandName": "Amazon", "couponTitle": "Flat ₹200 OFF on electronics", "category": "Electronics", "expiryDate": "2026-02-09", "daysUntilExpiry": 21, "description": "Applicable on headphones, mice and peripherals.", "couponCode": "AMZELEC200", "redeemable": true, "minimumOrderValue": "₹999", "couponLink": "https://amazon.in/deals/electronics" },
    { "brandName": "Amazon", "couponTitle": "₹100 Cashback on books", "category": "Books", "expiryDate": "2026-02-01", "daysUntilExpiry": 13, "description": "Valid for paperback books above ₹400.", "couponCode": "AMZBOOK100", "redeemable": true, "minimumOrderValue": "₹400", "couponLink": "https://amazon.in/deals/books" },
    { "brandName": "Amazon", "couponTitle": "10% OFF on fashion wear", "category": "Fashion", "expiryDate": "2026-02-18", "daysUntilExpiry": 30, "description": "Applicable on apparel and accessories.", "couponCode": "AMZFASHION10", "redeemable": true, "minimumOrderValue": "₹499", "couponLink": "https://amazon.in/deals/fashion10" },
    { "brandName": "Amazon", "couponTitle": "₹75 OFF on home essentials", "category": "Home", "expiryDate": "2026-02-05", "daysUntilExpiry": 17, "description": "Valid on cleaning supplies and utilities.", "couponCode": "AMZHOME75", "redeemable": true, "minimumOrderValue": "₹299", "couponLink": "https://amazon.in/deals/home75" },
    { "brandName": "Amazon", "couponTitle": "₹300 OFF on kitchen appliances", "category": "Kitchen", "expiryDate": "2026-02-11", "daysUntilExpiry": 23, "description": "Applies to mixers, kettles and cookware.", "couponCode": "AMZKITCH300", "redeemable": true, "minimumOrderValue": "₹1499", "couponLink": "https://amazon.in/deals/kitchen" },
    { "brandName": "Nykaa", "couponTitle": "Flat 15% OFF on skincare", "category": "Beauty", "expiryDate": "2026-01-28", "daysUntilExpiry": 9, "description": "Applicable on moisturizers, serums and SPF.", "couponCode": "NYSKIN15", "redeemable": true, "minimumOrderValue": "₹499", "couponLink": "https://nykaa.com/deals/skincare" },
    { "brandName": "Nykaa", "couponTitle": "Buy 2 Get 1 on makeup", "category": "Beauty", "expiryDate": "2026-02-13", "daysUntilExpiry": 25, "description": "Valid on foundations, lipsticks & palettes.", "couponCode": "NYB2G1", "redeemable": true, "minimumOrderValue": "₹799", "couponLink": "https://nykaa.com/deals/makeup" },
    { "brandName": "Nykaa", "couponTitle": "₹200 OFF on fragrances", "category": "Fragrance", "expiryDate": "2026-02-08", "daysUntilExpiry": 20, "description": "Applicable on branded perfumes above ₹999.", "couponCode": "NYFRAGR200", "redeemable": true, "minimumOrderValue": "₹999", "couponLink": "https://nykaa.com/deals/fragrance" },
    { "brandName": "Nykaa", "couponTitle": "10% OFF on hair care", "category": "Hair", "expiryDate": "2026-02-06", "daysUntilExpiry": 18, "description": "Valid on shampoos, conditioners & oils.", "couponCode": "NYHAIR10", "redeemable": true, "minimumOrderValue": "₹449", "couponLink": "https://nykaa.com/deals/hair" },
    { "brandName": "Nykaa", "couponTitle": "Flat ₹120 OFF on wellness products", "category": "Wellness", "expiryDate": "2026-02-17", "daysUntilExpiry": 29, "description": "Includes supplements and nutrition products.", "couponCode": "NYWELL120", "redeemable": true, "minimumOrderValue": "₹699", "couponLink": "https://nykaa.com/deals/wellness" },
    { "brandName": "CRED", "couponTitle": "Flat ₹200 Cashback on credit card bill", "category": "Finance", "expiryDate": "2026-02-04", "daysUntilExpiry": 16, "description": "Applicable once per billing cycle.", "couponCode": "CREDBILL200", "redeemable": true, "minimumOrderValue": "₹2000", "couponLink": "https://cred.club/billpay" },
    { "brandName": "CRED", "couponTitle": "₹150 Cashback on movie tickets", "category": "Entertainment", "expiryDate": "2026-02-07", "daysUntilExpiry": 19, "description": "Valid on PVR and INOX partners.", "couponCode": "CREDMOVIE150", "redeemable": true, "minimumOrderValue": "₹400", "couponLink": "https://cred.club/deals/movies" },
    { "brandName": "CRED", "couponTitle": "10% OFF on Apple accessories", "category": "Electronics", "expiryDate": "2026-02-19", "daysUntilExpiry": 31, "description": "Applicable on chargers, cables and cases.", "couponCode": "CREDAPPLE10", "redeemable": true, "minimumOrderValue": "₹799", "couponLink": "https://cred.club/store/apple" },
    { "brandName": "CRED", "couponTitle": "₹99 OFF on gourmet coffee", "category": "Food", "expiryDate": "2026-02-01", "daysUntilExpiry": 13, "description": "Applicable on selected roasted beans.", "couponCode": "CREDCOFFEE99", "redeemable": true, "minimumOrderValue": "₹299", "couponLink": "https://cred.club/store/coffee" },
    { "brandName": "CRED", "couponTitle": "Flat ₹250 OFF on gift cards", "category": "Gifts", "expiryDate": "2026-01-31", "daysUntilExpiry": 12, "description": "Valid on partnered brand gift cards.", "couponCode": "CREDGIFT250", "redeemable": true, "minimumOrderValue": "₹1000", "couponLink": "https://cred.club/giftcards" },
    { "brandName": "Swiggy", "couponTitle": "Flat 25% OFF on food orders", "category": "Food", "expiryDate": "2026-02-09", "daysUntilExpiry": 21, "description": "Applicable across selected restaurants nationwide.", "couponCode": "SWIG25", "redeemable": true, "minimumOrderValue": "₹199", "couponLink": "https://swiggy.com/deals/25off" },
    { "brandName": "Swiggy", "couponTitle": "₹120 OFF on Instamart order", "category": "Grocery", "expiryDate": "2026-02-03", "daysUntilExpiry": 15, "description": "Valid on grocery orders via Instamart.", "couponCode": "INSTAMART120", "redeemable": true, "minimumOrderValue": "₹499", "couponLink": "https://swiggy.com/instamart/deals" },
    { "brandName": "Swiggy", "couponTitle": "Buy 1 Get 1 FREE on biryani", "category": "Food", "expiryDate": "2026-02-12", "daysUntilExpiry": 24, "description": "Offer valid at selected partners.", "couponCode": "SWIGBIRYANI", "redeemable": true, "minimumOrderValue": "₹249", "couponLink": "https://swiggy.com/deals/biryani" },
    { "brandName": "Swiggy", "couponTitle": "₹75 OFF on desserts", "category": "Desserts", "expiryDate": "2026-02-06", "daysUntilExpiry": 18, "description": "Applicable on cakes, brownies & ice cream.", "couponCode": "SWIGSWEET75", "redeemable": true, "minimumOrderValue": "₹199", "couponLink": "https://swiggy.com/deals/desserts" },
    { "brandName": "Swiggy", "couponTitle": "10% OFF on Swiggy Genie", "category": "Courier", "expiryDate": "2026-01-30", "daysUntilExpiry": 11, "description": "Valid on pickup & drop services.", "couponCode": "GENIE10", "redeemable": true, "minimumOrderValue": "₹149", "couponLink": "https://swiggy.com/genie" },
    { "brandName": "Zepto", "couponTitle": "₹80 OFF on first grocery order", "category": "Grocery", "expiryDate": "2026-02-05", "daysUntilExpiry": 17, "description": "Valid for new Zepto users.", "couponCode": "ZEPNEW80", "redeemable": true, "minimumOrderValue": "₹299", "couponLink": "https://zepto.app/deals/new80" },
    { "brandName": "Zepto", "couponTitle": "Flat ₹50 OFF on fresh vegetables", "category": "Vegetables", "expiryDate": "2026-01-29", "daysUntilExpiry": 10, "description": "Applicable on fresh veggies above minimum order.", "couponCode": "ZEPVEG50", "redeemable": true, "minimumOrderValue": "₹199", "couponLink": "https://zepto.app/deals/veg50" },
    { "brandName": "Zepto", "couponTitle": "10% OFF on bakery items", "category": "Bakery", "expiryDate": "2026-02-14", "daysUntilExpiry": 26, "description": "Valid on bread, buns & baked goods.", "couponCode": "ZEPBAKE10", "redeemable": true, "minimumOrderValue": "₹149", "couponLink": "https://zepto.app/deals/bakery10" },
    { "brandName": "Zepto", "couponTitle": "₹60 OFF on soft drinks & beverages", "category": "Beverages", "expiryDate": "2026-02-08", "daysUntilExpiry": 20, "description": "Applicable on 1L+ SKUs.", "couponCode": "ZEPDRINK60", "redeemable": true, "minimumOrderValue": "₹249", "couponLink": "https://zepto.app/deals/drinks" },
    { "brandName": "Zepto", "couponTitle": "₹150 OFF on monthly essentials", "category": "Grocery", "expiryDate": "2026-02-18", "daysUntilExpiry": 30, "description": "Valid on bulk household supplies.", "couponCode": "ZEPESS150", "redeemable": true, "minimumOrderValue": "₹799", "couponLink": "https://zepto.app/deals/essentials" },
    { "brandName": "Licious", "couponTitle": "Flat ₹100 OFF on chicken orders", "category": "Meat", "expiryDate": "2026-02-02", "daysUntilExpiry": 14, "description": "Valid on fresh chicken cuts.", "couponCode": "LICCHICK100", "redeemable": true, "minimumOrderValue": "₹399", "couponLink": "https://licious.in/deals/chicken" },
    { "brandName": "Licious", "couponTitle": "₹150 OFF on seafood", "category": "Seafood", "expiryDate": "2026-02-09", "daysUntilExpiry": 21, "description": "Applicable on prawns, fish & more.", "couponCode": "LICSEA150", "redeemable": true, "minimumOrderValue": "₹499", "couponLink": "https://licious.in/deals/seafood" },
    { "brandName": "Licious", "couponTitle": "10% OFF on ready-to-cook items", "category": "RTC", "expiryDate": "2026-01-31", "daysUntilExpiry": 12, "description": "Valid on RTC marinades and kebabs.", "couponCode": "LICRTC10", "redeemable": true, "minimumOrderValue": "₹299", "couponLink": "https://licious.in/deals/rtc10" },
    { "brandName": "Licious", "couponTitle": "₹200 OFF on subscription boxes", "category": "Subscription", "expiryDate": "2026-02-15", "daysUntilExpiry": 27, "description": "Valid on protein subscription plans.", "couponCode": "LICSUB200", "redeemable": true, "minimumOrderValue": "₹999", "couponLink": "https://licious.in/deals/subscription" },
    { "brandName": "Licious", "couponTitle": "₹50 OFF on eggs & combos", "category": "Eggs", "expiryDate": "2026-02-07", "daysUntilExpiry": 19, "description": "Applicable on egg bundles and breakfast combos.", "couponCode": "LICEGG50", "redeemable": true, "minimumOrderValue": "₹199", "couponLink": "https://licious.in/deals/eggs" },
    { "brandName": "Dealora", "couponTitle": "Flat 20% OFF on partner deals", "category": " Deals", "expiryDate": "2026-02-11", "daysUntilExpiry": 23, "description": "Valid across promoted brand categories.", "couponCode": "DEAL20", "redeemable": true, "minimumOrderValue": "₹249", "couponLink": "https://dealora.app/deals/20" },
    { "brandName": "Dealora", "couponTitle": "₹100 Cashback on featured offers", "category": "Cashback", "expiryDate": "2026-02-05", "daysUntilExpiry": 17, "description": "Applicable once per user.", "couponCode": "DEALCASH100", "redeemable": true, "minimumOrderValue": "₹499", "couponLink": "https://dealora.app/deals/cashback" },
    { "brandName": "Dealora", "couponTitle": "Buy 1 Get 1 on merchant coupons", "category": "Offers", "expiryDate": "2026-02-18", "daysUntilExpiry": 30, "description": "Valid for selected merchant collaborations.", "couponCode": "DEALB1G1", "redeemable": true, "minimumOrderValue": "₹299", "couponLink": "https://dealora.app/deals/b1g1" },
    { "brandName": "Dealora", "couponTitle": "Flat ₹75 OFF on trending deals", "category": "Trending", "expiryDate": "2026-01-30", "daysUntilExpiry": 11, "description": "Offer valid on curated discounts.", "couponCode": "DEALTREND75", "redeemable": true, "minimumOrderValue": "₹199", "couponLink": "https://dealora.app/deals/trending" },
    { "brandName": "Dealora", "couponTitle": "Flat 15% OFF storewide", "category": "Store", "expiryDate": "2026-02-14", "daysUntilExpiry": 26, "description": "Valid across all store listings.", "couponCode": "DEALSTORE15", "redeemable": true, "minimumOrderValue": "₹349", "couponLink": "https://dealora.app/store" }
];

const seedDB = async () => {
    try {
        await connectDB();
        logger.info('Connected to database for seeding...');

        // Clear existing private coupons to avoid duplicates during development
        await PrivateCoupon.deleteMany({});
        logger.info('Cleared existing private coupons.');

        // Insert new coupons
        const insertedCoupons = await PrivateCoupon.insertMany(coupons);
        logger.info(`Successfully seeded ${insertedCoupons.length} private coupons.`);

        logger.info('Seeding completed. Closing connection...');
        mongoose.connection.close();
        process.exit(0);
    } catch (error) {
        logger.error('Seeding failed:', error);
        process.exit(1);
    }
};

seedDB();
